### ISSUE TITLE
Tweeting to Stephen's account

### ISSUE THREAD

**Issue by ilias-t** [stepheneyer/birdseed#3] opened 2015-07-17 18:32 UTC
Don't send all tweets to Stephen Eyer's account, that's mean :smiling_imp:

**Comment by stepheneyer** [comment] 2015-07-29 05:17
While it was fun to see everyone's creativity, the issue is now fixed. Users can now post to their own Twitter accounts instead of just mine. : ) I discovered the difference between single-user vs. multiple-user Twitter oauth and how to properly set the access token and access token secret based on user login.

**Closed as completed by stepheneyer** 2015-07-29 05:17 UTC
